export type ID = string

export interface Project {
  id: ID
  name: string
}

export interface ConversationSummary {
  id: ID
  first_start_time: string
  last_end_time: string
  span_count: number
  model?: string | null
}

export interface GroupListItem {
  trace_id: ID
  first_start_time: string
  last_end_time: string
  span_count: number
  model?: string | null
}

export interface SpanRecord {
  span_id: ID
  parent_span_id?: ID | null
  name?: string
  start_time?: string
  end_time?: string
  status_code?: string
  status_message?: string
  attributes?: string // JSON string from backend
  [k: string]: unknown
}

export type Theme = 'light' | 'dark'

// Generated by Copilot