import { useEffect } from 'react'
import type { Project } from '../types'
import { fetchProjects } from '../shared/api'

export default function ProjectsPage({
  projects,
  setProjects,
  onSelect,
}: {
  projects: Project[]
  setProjects: (p: Project[]) => void
  onSelect: (p: Project) => void
}) {
  useEffect(() => {
    let cancelled = false
    fetchProjects()
      .then((data) => {
        if (!cancelled) setProjects(data || [])
      })
      .catch((err) => console.error('Failed to fetch projects:', err))
    return () => {
      cancelled = true
    }
  }, [setProjects])

  return (
    <div className="projects-page">
      <h2>Projects</h2>
      {projects.length === 0 ? (
        <div style={{ color: 'var(--muted)', padding: '1rem' }}>
          No projects found. Projects are created automatically when spans are ingested.
        </div>
      ) : (
        <div className="projects-grid">
          {projects.map((p) => (
            <button key={p.id} className="project-card" onClick={() => onSelect(p)} type="button">
              <div className="project-icon">📁</div>
              <div className="project-name">{p.name}</div>
              <div className="project-badge">ID: {p.id}</div>
            </button>
          ))}
        </div>
      )}
    </div>
  )
}

// Generated by Copilot