import { useMemo } from 'react'

export type ConnectionStatus = 'connecting' | 'connected' | 'disconnected'

export default function ConnectionIndicator({ status }: { status: ConnectionStatus }) {
  const s = useMemo(() => {
    switch (status) {
      case 'connected':
        return { text: 'Connected', dot: 'connected' }
      case 'disconnected':
        return { text: 'Disconnected', dot: 'disconnected' }
      default:
        return { text: 'Connecting...', dot: 'connecting' }
    }
  }, [status])

  return (
    <div className="connection-wrap" title={s.text}>
      <span className={`status-dot ${s.dot}`} />
      <span className="status-text">{s.text}</span>
    </div>
  )
}

// Generated by Copilot