import { Theme } from '../types'

export default function ThemeToggle({ theme, onToggle }: { theme: Theme; onToggle: (next: Theme) => void }) {
  return (
    <button
      className="theme-toggle-switch"
      onClick={() => onToggle(theme === 'dark' ? 'light' : 'dark')}
      title="Toggle theme"
      aria-label="Toggle theme"
      type="button"
    >
      <span className="toggle-icon sun-icon">☀️</span>
      <span className="toggle-icon moon-icon">🌙</span>
    </button>
  )
}

// Generated by Copilot